services:
  prometheus-server:
    build: prometheus-server/.
    volumes:
      - ./prometheus-server/.:/etc/prometheus
    ports:
      - 9090:9090
  
  alertmanager:
    build: alertmanager/.
    volumes:
      - ./alertmanager/.:/etc/alertmanager
    ports:
      - 9093:9093
      