services:
  prometheus-server:
    build: prometheus-server/.
    volumes:
      - ./prometheus-server/.:/etc/prometheus
    ports:
      - 9090:9090
  
  alertmanager:
    build: alertmanager/.
    volumes:
      - ./alertmanager/.:/etc/alertmanager
    ports:
      - 9093:9093

  node-exporter:
    container_name: nginx-prometheus-exporter
    build: node-exporter/.
    ports:
      - "9113:9113"
    
  nginx:
    build: ngnix/.
    ports:
      - "9114:80"
      
