global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'
scrape_configs:
  # Here it's Prometheus itself.
  # job for node_exporter
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-server:9090']
  # job for node_exporter
  - job_name: 'nginx-prometheus-exporter'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']      

# configuration file rules 
rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
